### PR TITLE
expose subject to subscriber callbacks

### PR DESCRIPTION
**Pull request by israellot**
This addresses https://github.com/Cysharp/AlterNats/issues/6

### CODE REVIEW

**Comment by israellot** [comment]
@neuecc any thoughts on this? 
Let me know if you would prefer a direction other then simply adding a two parameter callback option. 
I believe another feasible solution would be a callback that takes a readonly struct as parameter, something like 
```
readonly struct NatsMessage<T> {
    public readonly T Data;
    public readonly NatsKey Topic;    
}
```
That would be a breaking change though.

**Comment by oising** [comment]
Bump.

**Comment by oising** [comment]
@neuecc ?

**Comment by to11mtm** [comment]
I took a peek at this and had a couple of comments:

1. It looks like in `MessagePublisher.cs` , the `options.UseThreadPoolCallback == true` (i.e. else cases) are not handled.
   a. This is easy to fix, but it does require changes to `ThreadPoolCallback<T>` in it's current form.
2. The way this is done, is going to create delegate allocations for the subscribe overloads that do not take `NatsKey` as a callback parameter.
   a.  It does look like the internals of `MessagePublisher` use `object[]` rather than `Action<T>` for the callbacks, so it -may- be solvable by just pushing the different types of callbacks down (i.e. having `SubscriptionManager.AddAsync` overloads for both `Action<T>` and `Action<NatsKey,T>` *but should be measured both ways for memory and speed*
3. Similar to point 2, if the Subject is not being used by the callbacks, the changes to `ParseMessageHeader` mean that there is an extra alloc for the subject whether or not any handlers actually care about it.
   a. This is probably more difficult to solve for; I'm guessing that either the hit has to be taken for both cases, or (short of extreme plumbing changes) the subject bytes would have to be copied into some lazy intermediate.

**Comment by to11mtm** [comment]
I have gone ahead and rebased this branch and fixed at least point 1 here: https://github.com/to11mtm/AlterNats/tree/expose-topic-to-subscribers

I'm happy to work with @israellot and others to get it where a merge would be good, if there is guidance on points 2 and 3 in my previous post!

**Comment by israellot** [comment]
Thanks @to11mtm ! 
I believe we need to hear from @neuecc. I feel this library was created to serve the purposes of MagicOnion and not exactly a generalist nats library. 
On their use case subscription subjects are not needed. 
Meanwhile, I've collaborated on another project https://github.com/80dB/AsyncNats where we achieved great performance too. 
Feel free to check it out if in search for a modern Nats client.

**Comment by oising** [comment]
> Thanks @to11mtm ! I believe we need to hear from @neuecc. I feel this library was created to serve the purposes of MagicOnion and not exactly a generalist nats library. On their use case subscription subjects are not needed. Meanwhile, I've collaborated on another project https://github.com/80dB/AsyncNats where we achieved great performance too. Feel free to check it out if in search for a modern Nats client.

I think many of us are in search of a modern Nats client that supports Jetstream... there seem to be plenty of pubsub implementations out there already.

**Comment by to11mtm** [comment]
> Thanks @to11mtm ! I believe we need to hear from @neuecc. I feel this library was created to serve the purposes of MagicOnion and not exactly a generalist nats library. On their use case subscription subjects are not needed. Meanwhile, I've collaborated on another project https://github.com/80dB/AsyncNats where we achieved great performance too. Feel free to check it out if in search for a modern Nats client.

@israellot Thank you for the heads up on this! Unfortunately it looks like the repository in question has been marked read-only; is there any plans to fork/continue it with the original authors?

**Comment by israellot** [comment]
@to11mtm yes, I plan to fork and continue its development. 

@oising Such library is yet to be produced. I've had some discussion with Nats authors and they have no short term plans to modernize their official library indeed.

**Pull request closed without merging**
